print("Hello M.6/14 ")
print("Pasika Moonsri")
print("My nickname is Aum")
print("I am 17 years old")
print("my birthday is 22/09/2004 ")
print("I study at Chonradsadornumrung school")
print("My blodtyp is A")
print("I like to eat papaya salad")
print("IG:aum_pasi.")
print("FB:Pasika Moonsri")
#ชื่อ พศิกา มุลศรี เลขที่ 39 ชั้น ม.6/14